#!/bin/bash
# fix based on https://forums.autodesk.com/t5/eagle-forum/running-eagle-on-fedora-33-dialogs-fail-display-properly-appears/m-p/10156138#M33482
rm -r ./lib/libQt* ./plugins qt.conf
rm ./libexec/QtWebEngineProcess ./libexec/qt.conf
sudo dnf install qt5-*
cd .local/share/Eagle/WebCache/
rm -r ControlPanel
